services:
  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data/:rw
  app:
    container_name: app
    image: app
    build: app
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "80:8080"
    depends_on:
      - redis
volumes:
  redis_data:
